package cli

import (
	"strings"
	"testing"
)

func TestCommandExamplesHighRiskPaths(t *testing.T) {
	tests := []struct {
		path string
		want []string
	}{
		{path: "cdp version", want: []string{"version --json"}},
		{path: "cdp guide", want: []string{"guide --path", "guide --json"}},
		{path: "cdp daemon start", want: []string{"--auto-connect"}},
		{path: "cdp daemon stop", want: []string{"--force-managed", "--stale-lock-after"}},
		{path: "cdp daemon restart", want: []string{"--autoConnect", "--force-managed", "--stale-lock-after"}},
		{path: "cdp daemon keepalive", want: []string{"--browser-mode headed", "--browser-mode headless"}},
		{path: "cdp daemon maintenance", want: []string{"--browser-mode headless", "--dry-run", "--profile-seed-strategy copy-default", "--stale-lock-after 1s"}},
		{path: "cdp daemon logs", want: []string{"--tail"}},
		{path: "cdp cron status", want: []string{"managed_processes", "last_run_artifacts"}},
		{path: "cdp cron install", want: []string{"cdp cron install --json", "--config cdp.json", "--artifact-retention 168h", "--max-log-size 64MiB"}},
		{path: "cdp cron run", want: []string{"headed-daemon-keepalive", "headless-maintenance", "artifact-prune"}},
		{path: "cdp artifacts prune", want: []string{"--older-than 168h", "--max-log-size 64MiB", "--dry-run", "--apply"}},
		{path: "cdp artifacts run-managed", want: []string{"--task example", "--log tmp/example.log"}},
		{path: "cdp cron heal headed", want: []string{"--reconnect 30s"}},
		{path: "cdp browser preflight", want: []string{"--repair", "--cleanup", "--profile-seed managed"}},
		{path: "cdp targets", want: []string{"--retry transient"}},
		{path: "cdp pages", want: []string{"--title-contains", "--retry transient"}},
		{path: "cdp page cleanup", want: []string{"--browser-mode headed", "--browser-mode headless", "--close", "--root-task-id"}},
		{path: "cdp open", want: []string{"--task-id", "--reuse", "--budget-summary"}},
		{path: "cdp stop-state classify", want: []string{"--rule-text-contains", "--target", "Sign in to continue"}},
		{path: "cdp eval", want: []string{"--title-contains", "--target-index 2"}},
		{path: "cdp observe", want: []string{"--target-index 2"}},
		{path: "cdp fill", want: []string{"--target-index 2"}},
		{path: "cdp type", want: []string{"--target-index 2"}},
		{path: "cdp insert-text", want: []string{"--target-index 2"}},
		{path: "cdp press", want: []string{"--target-index 2"}},
		{path: "cdp focus", want: []string{"--target-index 2"}},
		{path: "cdp clear", want: []string{"--target-index 2"}},
		{path: "cdp form values", want: []string{"--target-index 2"}},
		{path: "cdp form get", want: []string{"--target-index 2"}},
		{path: "cdp dialog accept", want: []string{"--wait", "--type prompt", "--target-index 2"}},
		{path: "cdp dialog dismiss", want: []string{"--wait", "--type confirm", "--target-index 2"}},
		{path: "cdp emulate viewport", want: []string{"--preset iphone-12", "--target-index 2"}},
		{path: "cdp emulate clear", want: []string{"--target-index 2"}},
		{path: "cdp emulate media", want: []string{"--prefers-color-scheme dark", "--target-index 2"}},
		{path: "cdp emulate color-scheme", want: []string{"--scheme light", "--target-index 2"}},
		{path: "cdp emulate user-agent", want: []string{"--user-agent", "--target-index 2"}},
		{path: "cdp emulate geolocation", want: []string{"--latitude", "--target-index 2"}},
		{path: "cdp emulate timezone", want: []string{"--timezone-id UTC", "--target-index 2"}},
		{path: "cdp emulate locale", want: []string{"--locale en-US", "--target-index 2"}},
		{path: "cdp emulate cpu", want: []string{"--rate 1", "--target-index 2"}},
		{path: "cdp emulate network", want: []string{"--preset slow-3g", "--target-index 2"}},
		{path: "cdp check", want: []string{"--target-index 2"}},
		{path: "cdp uncheck", want: []string{"--target-index 2"}},
		{path: "cdp select", want: []string{"--target-index 2"}},
		{path: "cdp hover", want: []string{"--target-index 2"}},
		{path: "cdp drag", want: []string{"--target-index 2"}},
		{path: "cdp scroll", want: []string{"--target-index 2"}},
		{path: "cdp wait eval", want: []string{"--ready-expr", "--out-dir", "--retry transient", "--classify-stop-state"}},
		{path: "cdp wait text", want: []string{"Ready", "--target-index 2"}},
		{path: "cdp wait selector", want: []string{"--target-index 2"}},
		{path: "cdp wait url", want: []string{"--mode contains", "--target-index 2"}},
		{path: "cdp wait locator", want: []string{"--by text", "--target-index 2"}},
		{path: "cdp wait eval", want: []string{"--target-index 2"}},
		{path: "cdp wait load-state", want: []string{"--poll", "--target-index 2"}},
		{path: "cdp assert value", want: []string{"--target-index 2"}},
		{path: "cdp assert text", want: []string{"--target-index 2"}},
		{path: "cdp assert url", want: []string{"--target-index 2"}},
		{path: "cdp assert title", want: []string{"--target-index 2"}},
		{path: "cdp assert count", want: []string{"--target-index 2"}},
		{path: "cdp assert attribute", want: []string{"--target-index 2"}},
		{path: "cdp assert class", want: []string{"--target-index 2"}},
		{path: "cdp assert focused", want: []string{"--target-index 2"}},
		{path: "cdp assert css", want: []string{"--target-index 2"}},
		{path: "cdp assert role", want: []string{"--target-index 2"}},
		{path: "cdp assert name", want: []string{"--target-index 2"}},
		{path: "cdp assert aria-snapshot", want: []string{"--target-index 2"}},
		{path: "cdp assert attached", want: []string{"--target-index 2"}},
		{path: "cdp assert detached", want: []string{"--target-index 2"}},
		{path: "cdp assert visible", want: []string{"--target-index 2"}},
		{path: "cdp assert hidden", want: []string{"--target-index 2"}},
		{path: "cdp assert in-viewport", want: []string{"--target-index 2"}},
		{path: "cdp assert enabled", want: []string{"--target-index 2"}},
		{path: "cdp assert disabled", want: []string{"--target-index 2"}},
		{path: "cdp assert editable", want: []string{"--target-index 2"}},
		{path: "cdp assert readonly", want: []string{"--target-index 2"}},
		{path: "cdp assert checked", want: []string{"--target-index 2"}},
		{path: "cdp assert unchecked", want: []string{"--target-index 2"}},
		{path: "cdp assert indeterminate", want: []string{"--target-index 2"}},
		{path: "cdp text", want: []string{"--target-index 2"}},
		{path: "cdp html", want: []string{"--diagnose-empty", "--target-index 2"}},
		{path: "cdp snapshot", want: []string{"--target-index 2"}},
		{path: "cdp frames", want: []string{"--target-index 2"}},
		{path: "cdp locator find", want: []string{"--target-index 2"}},
		{path: "cdp dom query", want: []string{"--target-index 2"}},
		{path: "cdp css inspect", want: []string{"--target-index 2"}},
		{path: "cdp layout overflow", want: []string{"--target-index 2"}},
		{path: "cdp a11y tree", want: []string{"--target-index 2"}},
		{path: "cdp a11y find", want: []string{"--target-index 2"}},
		{path: "cdp a11y node", want: []string{"--target-index 2"}},
		{path: "cdp a11y snapshot", want: []string{"--target-index 2"}},
		{path: "cdp perf summary", want: []string{"--target-index 2"}},
		{path: "cdp memory counters", want: []string{"--target-index 2"}},
		{path: "cdp memory heap-snapshot", want: []string{"--target-index 2"}},
		{path: "cdp screenshot", want: []string{"--element", "--target-index 2"}},
		{path: "cdp console", want: []string{"--errors", "--target-index 2"}},
		{path: "cdp network", want: []string{"--failed", "--target-index 2"}},
		{path: "cdp network capture", want: []string{"--redact", "--target-index 2"}},
		{path: "cdp network websocket", want: []string{"--include-payloads", "--target-index 2"}},
		{path: "cdp wait request", want: []string{"--match-url", "--target-index 2"}},
		{path: "cdp wait response", want: []string{"--status", "--target-index 2"}},
		{path: "cdp wait network-idle", want: []string{"--idle", "--target-index 2"}},
		{path: "cdp wait dialog", want: []string{"--action dismiss", "--target-index 2"}},
		{path: "cdp wait file-chooser", want: []string{"--mode single", "--target-index 2"}},
		{path: "cdp wait popup", want: []string{"--match-url", "--target-index 2"}},
		{path: "cdp wait download", want: []string{"--download-dir", "--target-index 2"}},
		{path: "cdp screenshot render", want: []string{"--serve"}},
		{path: "cdp storage", want: []string{"--target-index 2", "--redact safe"}},
		{path: "cdp storage list", want: []string{"--target-index 2"}},
		{path: "cdp storage get", want: []string{"--target-index 2"}},
		{path: "cdp storage set", want: []string{"--target-index 2"}},
		{path: "cdp storage delete", want: []string{"--target-index 2"}},
		{path: "cdp storage clear", want: []string{"--target-index 2"}},
		{path: "cdp storage snapshot", want: []string{"--target-index 2", "--redact safe"}},
		{path: "cdp storage cookies list", want: []string{"--target-index 2", "--url"}},
		{path: "cdp storage cookies set", want: []string{"--name", "--target-index 2", "--url"}},
		{path: "cdp storage cookies delete", want: []string{"--target-index 2", "--url"}},
		{path: "cdp storage indexeddb list", want: []string{"--target-index 2"}},
		{path: "cdp storage indexeddb get", want: []string{"--target-index 2"}},
		{path: "cdp storage indexeddb put", want: []string{"@tmp/value.json", "--target-index 2"}},
		{path: "cdp storage indexeddb dump", want: []string{"--target-index 2"}},
		{path: "cdp storage indexeddb delete", want: []string{"--target-index 2"}},
		{path: "cdp storage indexeddb clear", want: []string{"--target-index 2"}},
		{path: "cdp storage cache list", want: []string{"--target-index 2"}},
		{path: "cdp storage cache get", want: []string{"--target-index 2"}},
		{path: "cdp storage cache put", want: []string{"--content-type", "--target-index 2"}},
		{path: "cdp storage cache delete", want: []string{"--target-index 2"}},
		{path: "cdp storage cache clear", want: []string{"--target-index 2"}},
		{path: "cdp storage service-workers list", want: []string{"--target-index 2"}},
		{path: "cdp storage service-workers unregister", want: []string{"--scope", "--target-index 2"}},
		{path: "cdp protocol exec", want: []string{"--target", "--target-type service_worker"}},
		{path: "cdp file", want: []string{"--target-index 2"}},
		{path: "cdp file chooser", want: []string{"--target <target-id>", "--target-index 2", "--trial", "first.epub", "second.epub"}},
		{path: "cdp protocol examples", want: []string{"Page.captureScreenshot"}},
		{path: "cdp events wait", want: []string{"--file", "--method", "--from-offset", "--print-offset"}},
		{path: "cdp events tap", want: []string{"--target-index", "--enable", "--match", "--duration", "--max-events", "--ready-file"}},
		{path: "cdp events interactions", want: []string{"--target-index", "--match", "--duration", "--max-events", "--ready-file"}},
		{path: "cdp workflow page-load", want: []string{"--reload"}},
		{path: "cdp workflow rendered-extract", want: []string{"--serp google", "x.com/karpathy/status", "x.com/karpathy'", "linkedin.com/company", "reddit.com/user", "reddit.com/r/example/comments"}},
		{path: "cdp workflow reddit posts", want: []string{"reddit.com/r/formula1/top/?t=week", "--limit 200", "reddit.com/r/golang/new/"}},
		{path: "cdp workflow reddit collect", want: []string{"reddit.com/r/formula1/top/?t=week", "reddit.com/r/codex/comments", "reddit.com/user/celticpaladin/comments"}},
		{path: "cdp workflow x collect", want: []string{"x.com/karpathy/status", "x.com/karpathy", "--limit 200"}},
		{path: "cdp workflow linkedin collect", want: []string{"linkedin.com/posts", "linkedin.com/company", "--limit 200"}},
		{path: "cdp workflow arxiv collect", want: []string{"arxiv.org/abs", "--json"}},
		{path: "cdp workflow web-research serp", want: []string{"--result-pages 3", "cdr:1,cd_min:07/01/2026,cd_max:07/01/2026", "--google-ai auto", "--google-ai mode"}},
		{path: "cdp workflow web-research extract", want: []string{"--parallel 4", "--parallel 10"}},
		{path: "cdp workflow feeds", want: []string{"--wait-load"}},
		{path: "cdp workflow youtube cookies", want: []string{"--out", "--browser-mode headed"}},
		{path: "cdp workflow visible-posts", want: []string{"visible-posts"}},
		{path: "cdp workflow hacker-news", want: []string{"hacker-news"}},
		{path: "cdp workflow hacker-news collect", want: []string{"news.ycombinator.com/item?id", "--limit 500"}},
		{path: "cdp workflow verify", want: []string{"workflow verify"}},
		{path: "cdp workflow debug-bundle", want: []string{"debug-bundle"}},
		{path: "cdp workflow action-capture", want: []string{"--evidence-out-dir", "--include-bodies json,text", "--body-url-contains /api/"}},
		{path: "cdp workflow submit-search", want: []string{"--wait-url-contains", "--suggestion", "--submit none", "--wait-load-state", "--wait-response"}},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			examples := commandExamples(tt.path)
			if len(examples) == 0 {
				t.Fatalf("commandExamples(%q) returned no examples", tt.path)
			}
			for _, want := range tt.want {
				if !examplesContain(examples, want) {
					t.Fatalf("commandExamples(%q) = %#v, want an example containing %q", tt.path, examples, want)
				}
			}
		})
	}
}

func examplesContain(examples []string, needle string) bool {
	for _, example := range examples {
		if strings.Contains(example, needle) {
			return true
		}
	}
	return false
}
