package cli

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/pankaj28843/cdp-cli/internal/transcriptionapi"
	"github.com/pankaj28843/cdp-cli/internal/transcriptionservice"
	"github.com/spf13/cobra"
)

func (a *app) newTranscriptionServiceCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "service",
		Short: "Install and control the transcription API service",
		Long: "Manage cdp transcription serve as a native service. macOS uses a LaunchAgent; " +
			"Linux uses systemd --user by default or a machine-wide systemd unit with --system. " +
			"The service reads its configuration from environment values generated by install. " +
			"Service-manager diagnostics are bounded and canceled within the owned process group.",
		Example: "  cdp transcription service install --address '[::]:28765'\n" +
			"  cdp transcription service install --system --address '0.0.0.0:28765'\n" +
			"  cdp transcription service status\n" +
			"  cdp transcription service uninstall",
	}
	cmd.PersistentFlags().Bool("system", false, "use the machine-wide Linux systemd service (requires root)")
	cmd.AddCommand(a.newTranscriptionServiceInstallCommand())
	cmd.AddCommand(a.newTranscriptionServiceStartCommand("start", "Start and enable the transcription API service"))
	cmd.AddCommand(a.newTranscriptionServiceStartCommand("restart", "Restart the transcription API service"))
	cmd.AddCommand(a.newTranscriptionServiceStopCommand())
	cmd.AddCommand(a.newTranscriptionServiceStatusCommand())
	cmd.AddCommand(a.newTranscriptionServiceUninstallCommand())
	return cmd
}

func (a *app) newTranscriptionServiceInstallCommand() *cobra.Command {
	var address string
	var httpAddress string
	var provider string
	var allowedProviders []string
	var localBaseURL string
	var localRealtimeBaseURL string
	var localAPIKey string
	var maxAudioBytes int64
	var authRefreshInterval time.Duration
	var authRefreshOffset time.Duration
	var fixtureDir string
	var probeInterval time.Duration
	var persistAudio bool
	var tlsCertFile string
	var tlsKeyFile string
	var tlsSelfSigned bool
	var tlsHosts []string
	var tlsRegenerate bool
	var binaryPath string
	var start bool
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Write the native service and start it",
		Long: "Write a LaunchAgent plist on macOS or a systemd unit plus owner-only " +
			"environment file on Linux. Use --system for a machine-wide service; it requires root " +
			"and starts the unauthenticated service by default.",
		Example: "  cdp transcription service install --address '[::]:28765' --http-address '[::]:28766' --start\n" +
			"  cdp transcription service install --address '[::]:28765' --http-address '[::]:28766' --tls-self-signed --tls-host 192.168.5.249",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			systemScope, err := cmd.Flags().GetBool("system")
			if err != nil {
				return err
			}
			fixtureDir = strings.TrimSpace(fixtureDir)
			fixtureCount := 0
			if fixtureDir != "" {
				if _, err := transcriptionapi.LoadFixtureCatalog(fixtureDir); err != nil {
					return fmt.Errorf("validate transcription service fixture corpus: %w", err)
				}
				fixtureCount = transcriptionapi.DefaultFixtureCount
			}
			if authRefreshOffset < 0 || (authRefreshInterval == 0 && authRefreshOffset != 0) || (authRefreshInterval > 0 && authRefreshOffset >= authRefreshInterval) {
				return fmt.Errorf("--auth-refresh-offset must be non-negative and shorter than its interval")
			}
			if probeInterval == 0 {
				probeInterval = transcriptionapi.DefaultProbeInterval
			}
			authRefreshEnabled := authRefreshInterval > 0
			platform, paths, config, err := a.transcriptionServiceConfig(systemScope, binaryPath, address, httpAddress, provider, allowedProviders, localBaseURL, localRealtimeBaseURL, localAPIKey, maxAudioBytes, authRefreshInterval, authRefreshOffset, authRefreshEnabled, fixtureDir, probeInterval, persistAudio, tlsCertFile, tlsKeyFile)
			if err != nil {
				return err
			}
			if systemScope {
				if err := validateSystemServiceAccount(); err != nil {
					return err
				}
			}
			if err := os.MkdirAll(config.StateDir, 0o700); err != nil {
				return fmt.Errorf("create transcription service state directory: %w", err)
			}
			tlsFiles, err := configureTranscriptionTLS(config.StateDir, config.TLSCertFile, config.TLSKeyFile, tlsSelfSigned, tlsHosts, tlsRegenerate)
			if err != nil {
				return err
			}
			config.TLSCertFile = tlsFiles.CertFile
			config.TLSKeyFile = tlsFiles.KeyFile
			artifacts, err := transcriptionservice.Render(platform, config, paths)
			if err != nil {
				return err
			}
			if err := writeTranscriptionServiceArtifacts(artifacts, paths.LogDirectory); err != nil {
				return err
			}
			if systemScope {
				if err := prepareSystemServiceOwnership(config.StateDir, paths); err != nil {
					return err
				}
			}
			if start {
				if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "restart", paths); err != nil {
					return err
				}
			}
			return a.render(cmd.Context(), "transcription service installed", map[string]any{
				"platform":             platform,
				"service":              serviceName(platform),
				"started":              start,
				"address":              config.Address,
				"http_address":         config.HTTPAddress,
				"provider":             config.Provider,
				"auth_refresh_enabled": authRefreshEnabled,
				"auth_refresh_offset":  authRefreshOffset.String(),
				"probe_interval":       config.ProbeInterval.String(),
				"fixture_count":        fixtureCount,
				"audio_persisted":      config.PersistAudio,
				"tls_enabled":          strings.TrimSpace(config.TLSCertFile) != "",
				"tls_cert_file":        tlsFiles.CertFile,
				"tls_hosts":            tlsFiles.Hosts,
				"tls_reused":           tlsFiles.Reused,
				"demo_url":             preferredDemoURL(config.Address, strings.TrimSpace(config.TLSCertFile) != "", tlsFiles.Hosts),
				"demo_urls":            demoURLs(config.Address, strings.TrimSpace(config.TLSCertFile) != "", tlsFiles.Hosts),
				"artifacts":            artifactPaths(artifacts),
			})
		},
	}
	cmd.Flags().StringVar(&address, "address", envDefault("CDP_TRANSCRIPTION_ADDRESS", transcriptionapi.DefaultListenAddress), "primary listen address; defaults to [::]:28765 (dual-stack wildcard where IPv6 is enabled)")
	cmd.Flags().StringVar(&httpAddress, "http-address", envDefault("CDP_TRANSCRIPTION_HTTP_ADDRESS", transcriptionapi.DefaultHTTPListenAddress), "cleartext companion listen address; defaults to [::]:28766 (dual-stack wildcard where IPv6 is enabled)")
	cmd.Flags().StringVar(&provider, "default-provider", envDefault("CDP_TRANSCRIPTION_PROVIDER", string(transcriptionapi.ProviderLocal)), "default provider: local, bing-web, chatgpt-web, claude-web, gemini-web, or microsoft-365-web")
	cmd.Flags().StringSliceVar(&allowedProviders, "providers", envStringSlice("CDP_TRANSCRIPTION_PROVIDERS"), "provider allowlist persisted into the user service; repeat or comma-separate")
	cmd.Flags().StringVar(&localBaseURL, "local-base-url", os.Getenv("CDP_TRANSCRIPTION_LOCAL_BASE_URL"), "local OpenAI-compatible provider base URL, usually ending in /v1")
	cmd.Flags().StringVar(&localRealtimeBaseURL, "local-realtime-base-url", os.Getenv("CDP_TRANSCRIPTION_LOCAL_REALTIME_BASE_URL"), "optional local realtime provider base URL, usually ending in /v1")
	cmd.Flags().StringVar(&localAPIKey, "local-api-key", os.Getenv("CDP_TRANSCRIPTION_LOCAL_API_KEY"), "API key for the configured local provider")
	cmd.Flags().Int64Var(&maxAudioBytes, "max-audio-bytes", envInt64("CDP_TRANSCRIPTION_MAX_AUDIO_BYTES", transcriptionapi.DefaultMaxAudioBytes), "maximum retained audio-cache bytes")
	cmd.Flags().DurationVar(&authRefreshInterval, "auth-refresh-interval", envDuration("CDP_TRANSCRIPTION_AUTH_REFRESH_INTERVAL", transcriptionapi.DefaultAuthRefreshInterval), "shared recurring freshness check for all online providers; use 0s to disable")
	cmd.Flags().DurationVar(&authRefreshOffset, "auth-refresh-offset", envDuration("CDP_TRANSCRIPTION_AUTH_REFRESH_OFFSET", 0), "wall-clock phase offset for recurring auth refreshes; must be shorter than the interval")
	cmd.Flags().StringVar(&fixtureDir, "fixture-dir", envDefault("CDP_TRANSCRIPTION_FIXTURE_DIR", defaultTranscriptionFixtureDir()), "checked-in WebM corpus used by the bounded provider health probe; explicitly empty disables scheduled probes")
	cmd.Flags().DurationVar(&probeInterval, "probe-interval", envDuration("CDP_TRANSCRIPTION_PROBE_INTERVAL", transcriptionapi.DefaultProbeInterval), "interval between bounded synthetic provider health probes")
	cmd.Flags().BoolVar(&persistAudio, "persist-audio", envBool("CDP_TRANSCRIPTION_PERSIST_AUDIO"), "retain uploaded audio under the state directory; default is ephemeral transaction media")
	cmd.Flags().StringVar(&tlsCertFile, "tls-cert", os.Getenv("CDP_TRANSCRIPTION_TLS_CERT"), "TLS certificate file; provide with --tls-key for HTTPS microphone access over LAN")
	cmd.Flags().StringVar(&tlsKeyFile, "tls-key", os.Getenv("CDP_TRANSCRIPTION_TLS_KEY"), "TLS private key file; provide with --tls-cert")
	cmd.Flags().BoolVar(&tlsSelfSigned, "tls-self-signed", false, "generate or reuse a private-LAN self-signed certificate under the cdp state directory")
	cmd.Flags().StringSliceVar(&tlsHosts, "tls-host", nil, "DNS name or IP to include in a self-signed certificate; repeat for multiple names")
	cmd.Flags().BoolVar(&tlsRegenerate, "tls-regenerate", false, "replace the generated self-signed certificate and key")
	cmd.Flags().StringVar(&binaryPath, "binary", "", "absolute cdp binary path; defaults to the running executable")
	cmd.Flags().BoolVar(&start, "start", true, "start and enable the service after installing its files")
	return cmd
}

func (a *app) newTranscriptionServiceStartCommand(name, short string) *cobra.Command {
	return &cobra.Command{
		Use:   name,
		Short: short,
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			systemScope, err := cmd.Flags().GetBool("system")
			if err != nil {
				return err
			}
			platform, paths, err := a.transcriptionServicePaths(systemScope)
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, name, paths); err != nil {
				return err
			}
			return a.render(cmd.Context(), "transcription service "+name+" complete", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) newTranscriptionServiceStopCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "stop",
		Short: "Stop the transcription API service",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			systemScope, err := cmd.Flags().GetBool("system")
			if err != nil {
				return err
			}
			platform, paths, err := a.transcriptionServicePaths(systemScope)
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "stop", paths); err != nil {
				return err
			}
			return a.render(cmd.Context(), "transcription service stopped", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) newTranscriptionServiceStatusCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show transcription API service status",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			systemScope, err := cmd.Flags().GetBool("system")
			if err != nil {
				return err
			}
			platform, paths, err := a.transcriptionServicePaths(systemScope)
			if err != nil {
				return err
			}
			installed := serviceInstalled(platform, paths)
			running, detail := transcriptionServiceRunning(cmd.Context(), platform, paths)
			tlsEnabled := transcriptionServiceTLSConfigured(platform, paths)
			return a.render(cmd.Context(), "transcription service status", map[string]any{
				"platform":    platform,
				"service":     serviceName(platform),
				"installed":   installed,
				"running":     running,
				"detail":      detail,
				"tls_enabled": tlsEnabled,
				"demo_url":    demoURL(transcriptionapi.DefaultListenAddress, tlsEnabled),
				"artifacts":   map[string]string{"launch_agent": paths.LaunchAgent, "systemd_unit": paths.SystemdUnit, "environment": paths.Environment},
			})
		},
	}
}

func (a *app) newTranscriptionServiceUninstallCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "uninstall",
		Short: "Stop and remove the transcription API service",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			systemScope, err := cmd.Flags().GetBool("system")
			if err != nil {
				return err
			}
			platform, paths, err := a.transcriptionServicePaths(systemScope)
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "stop", paths); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			for _, path := range serviceArtifactPaths(platform, paths) {
				if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
					return fmt.Errorf("remove transcription service artifact %s: %w", path, err)
				}
			}
			return a.render(cmd.Context(), "transcription service uninstalled", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) transcriptionServicePaths(systemScope bool) (transcriptionservice.Platform, transcriptionservice.Paths, error) {
	platform, err := transcriptionservice.CurrentPlatform()
	if err != nil {
		return "", transcriptionservice.Paths{}, err
	}
	if systemScope {
		if platform != transcriptionservice.PlatformLinux {
			return "", transcriptionservice.Paths{}, fmt.Errorf("system transcription service scope is supported only on Linux")
		}
		if os.Geteuid() != 0 {
			return "", transcriptionservice.Paths{}, fmt.Errorf("system transcription service scope requires root")
		}
		return platform, transcriptionservice.PathsForSystem(), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", transcriptionservice.Paths{}, fmt.Errorf("resolve home directory: %w", err)
	}
	paths, err := transcriptionservice.PathsForHome(home)
	if err != nil {
		return "", transcriptionservice.Paths{}, err
	}
	return platform, paths, nil
}

func (a *app) transcriptionServiceConfig(systemScope bool, binaryPath, address, httpAddress, provider string, allowedProviders []string, localBaseURL, localRealtimeBaseURL, localAPIKey string, maxAudioBytes int64, authRefreshInterval, authRefreshOffset time.Duration, authRefreshEnabled bool, fixtureDir string, probeInterval time.Duration, persistAudio bool, tlsCertFile, tlsKeyFile string) (transcriptionservice.Platform, transcriptionservice.Paths, transcriptionservice.Config, error) {
	platform, paths, err := a.transcriptionServicePaths(systemScope)
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, err
	}
	stateStore, err := a.stateStore()
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, err
	}
	if systemScope && filepath.Clean(stateStore.Dir) != transcriptionservice.SystemServiceHome {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("system transcription service state directory must be %s", transcriptionservice.SystemServiceHome)
	}
	if strings.TrimSpace(binaryPath) == "" {
		binaryPath, err = os.Executable()
		if err != nil {
			return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("resolve running cdp executable: %w", err)
		}
	}
	binaryPath, err = filepath.Abs(binaryPath)
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("resolve cdp executable path: %w", err)
	}
	fixtureDir = strings.TrimSpace(fixtureDir)
	if fixtureDir != "" {
		fixtureDir, err = filepath.Abs(fixtureDir)
		if err != nil {
			return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("resolve transcription fixture directory: %w", err)
		}
	}
	config := transcriptionservice.Config{
		BinaryPath:           binaryPath,
		StateDir:             stateStore.Dir,
		Address:              strings.TrimSpace(address),
		HTTPAddress:          strings.TrimSpace(httpAddress),
		Provider:             strings.TrimSpace(provider),
		AllowedProviders:     append([]string(nil), allowedProviders...),
		BrowserMode:          a.browserModeName(),
		BrowserURL:           strings.TrimSpace(a.opts.browserURL),
		Display:              strings.TrimSpace(os.Getenv("DISPLAY")),
		XAuthority:           strings.TrimSpace(os.Getenv("XAUTHORITY")),
		AllowOverBudget:      a.opts.allowOverBudget,
		LocalBaseURL:         strings.TrimSpace(localBaseURL),
		LocalRealtimeBaseURL: strings.TrimSpace(localRealtimeBaseURL),
		LocalAPIKey:          strings.TrimSpace(localAPIKey),
		MaxAudioBytes:        maxAudioBytes,
		AuthRefreshInterval:  authRefreshInterval,
		AuthRefreshOffset:    authRefreshOffset,
		AuthRefreshEnabled:   authRefreshEnabled,
		FixtureDir:           fixtureDir,
		ProbeInterval:        probeInterval,
		PersistAudio:         persistAudio,
		TLSCertFile:          strings.TrimSpace(tlsCertFile),
		TLSKeyFile:           strings.TrimSpace(tlsKeyFile),
		Path:                 os.Getenv("PATH"),
	}
	return platform, paths, config, nil
}

func defaultTranscriptionFixtureDir() string {
	workingDirectory, err := os.Getwd()
	if err != nil {
		return ""
	}
	candidate := filepath.Join(workingDirectory, "testdata", "transcription-fixtures")
	if _, err := os.Stat(filepath.Join(candidate, "manifest.json")); err != nil {
		return ""
	}
	absolute, err := filepath.Abs(candidate)
	if err != nil {
		return ""
	}
	return absolute
}

func writeTranscriptionServiceArtifacts(artifacts []transcriptionservice.Artifact, logDirectory string) error {
	if err := os.MkdirAll(logDirectory, 0o700); err != nil {
		return fmt.Errorf("create transcription service log directory: %w", err)
	}
	for _, artifact := range artifacts {
		if err := os.MkdirAll(filepath.Dir(artifact.Path), 0o700); err != nil {
			return fmt.Errorf("create transcription service directory for %s: %w", artifact.Path, err)
		}
		if err := os.WriteFile(artifact.Path, artifact.Data, artifact.Mode); err != nil {
			return fmt.Errorf("write transcription service artifact %s: %w", artifact.Path, err)
		}
		if err := os.Chmod(artifact.Path, artifact.Mode); err != nil {
			return fmt.Errorf("set transcription service artifact mode %s: %w", artifact.Path, err)
		}
	}
	return nil
}

func validateSystemServiceAccount() error {
	if _, err := user.Lookup(transcriptionservice.SystemServiceUser); err != nil {
		return fmt.Errorf("system transcription service account %q is missing; create it with a system nologin user before installing: %w", transcriptionservice.SystemServiceUser, err)
	}
	return nil
}

func prepareSystemServiceOwnership(stateDir string, paths transcriptionservice.Paths) error {
	serviceUser, err := user.Lookup(transcriptionservice.SystemServiceUser)
	if err != nil {
		return fmt.Errorf("resolve system transcription service account: %w", err)
	}
	uid, err := strconv.Atoi(serviceUser.Uid)
	if err != nil {
		return fmt.Errorf("parse system transcription service uid: %w", err)
	}
	gid, err := strconv.Atoi(serviceUser.Gid)
	if err != nil {
		return fmt.Errorf("parse system transcription service gid: %w", err)
	}
	if err := chownTree(stateDir, uid, gid); err != nil {
		return fmt.Errorf("assign system transcription state to %s: %w", transcriptionservice.SystemServiceUser, err)
	}
	if err := os.Chmod(stateDir, 0o750); err != nil {
		return fmt.Errorf("set system transcription state directory mode: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(stateDir, ".config"), 0o750); err != nil {
		return fmt.Errorf("create system transcription config directory: %w", err)
	}
	if err := chownTree(filepath.Join(stateDir, ".config"), uid, gid); err != nil {
		return fmt.Errorf("assign system transcription config to %s: %w", transcriptionservice.SystemServiceUser, err)
	}
	if err := os.Chown(filepath.Dir(paths.Environment), 0, gid); err != nil {
		return fmt.Errorf("assign transcription environment directory group: %w", err)
	}
	if err := os.Chmod(filepath.Dir(paths.Environment), 0o750); err != nil {
		return fmt.Errorf("set transcription environment directory mode: %w", err)
	}
	if err := os.Chown(paths.Environment, 0, gid); err != nil {
		return fmt.Errorf("assign transcription environment group: %w", err)
	}
	if err := os.Chmod(paths.Environment, 0o640); err != nil {
		return fmt.Errorf("set transcription environment mode: %w", err)
	}
	if err := os.Chown(paths.LogDirectory, uid, gid); err != nil {
		return fmt.Errorf("assign transcription log directory: %w", err)
	}
	if err := os.Chmod(paths.LogDirectory, 0o750); err != nil {
		return fmt.Errorf("set transcription log directory mode: %w", err)
	}
	return nil
}

func chownTree(root string, uid, gid int) error {
	return filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil
		}
		return os.Chown(path, uid, gid)
	})
}

func artifactPaths(artifacts []transcriptionservice.Artifact) []string {
	paths := make([]string, 0, len(artifacts))
	for _, artifact := range artifacts {
		paths = append(paths, artifact.Path)
	}
	return paths
}

func serviceArtifactPaths(platform transcriptionservice.Platform, paths transcriptionservice.Paths) []string {
	if platform == transcriptionservice.PlatformMacOS {
		return []string{paths.LaunchAgent}
	}
	return []string{paths.SystemdUnit, paths.Environment}
}

func serviceInstalled(platform transcriptionservice.Platform, paths transcriptionservice.Paths) bool {
	for _, path := range serviceArtifactPaths(platform, paths) {
		if _, err := os.Stat(path); err != nil {
			return false
		}
	}
	return true
}

func serviceName(platform transcriptionservice.Platform) string {
	if platform == transcriptionservice.PlatformMacOS {
		return transcriptionservice.LaunchAgentLabel
	}
	return transcriptionservice.SystemdUnitName
}

func runTranscriptionServiceAction(ctx context.Context, platform transcriptionservice.Platform, action string, paths transcriptionservice.Paths) (string, error) {
	switch platform {
	case transcriptionservice.PlatformMacOS:
		return runLaunchctlAction(ctx, action, paths)
	case transcriptionservice.PlatformLinux:
		return runSystemctlAction(ctx, action, paths)
	default:
		return "", fmt.Errorf("unsupported transcription service platform %q", platform)
	}
}

func runLaunchctlAction(ctx context.Context, action string, paths transcriptionservice.Paths) (string, error) {
	domain := fmt.Sprintf("gui/%d", os.Getuid())
	target := domain + "/" + transcriptionservice.LaunchAgentLabel
	switch action {
	case "start":
		if _, err := runServiceCommand(ctx, "launchctl", "print", target); err != nil {
			if err := bootstrapLaunchAgent(ctx, domain, paths.LaunchAgent); err != nil {
				return "", err
			}
		}
		return runServiceCommand(ctx, "launchctl", "kickstart", "-k", target)
	case "restart":
		_, _ = runServiceCommand(ctx, "launchctl", "bootout", target)
		if err := bootstrapLaunchAgent(ctx, domain, paths.LaunchAgent); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "launchctl", "kickstart", "-k", target)
	case "stop":
		_, err := runServiceCommand(ctx, "launchctl", "bootout", target)
		if err != nil && !strings.Contains(strings.ToLower(err.Error()), "could not find service") {
			return "", err
		}
		return "stopped", nil
	default:
		return "", fmt.Errorf("unsupported launchctl action %q", action)
	}
}

// bootstrapLaunchAgent prefers the modern bootstrap API but keeps a legacy
// load fallback for macOS versions/configurations that return an opaque I/O
// error when bootstrapping a per-user LaunchAgent. Both paths still register
// the same plist; the fallback is only for launchctl compatibility.
func bootstrapLaunchAgent(ctx context.Context, domain, plistPath string) error {
	if _, err := runServiceCommand(ctx, "launchctl", "bootstrap", domain, plistPath); err == nil {
		return nil
	} else {
		if _, loadErr := runServiceCommand(ctx, "launchctl", "load", plistPath); loadErr == nil {
			return nil
		} else {
			return fmt.Errorf("launchctl bootstrap failed: %w; legacy load fallback failed: %v", err, loadErr)
		}
	}
}

func runSystemctlAction(ctx context.Context, action string, paths transcriptionservice.Paths) (string, error) {
	unit := transcriptionservice.SystemdUnitName
	scopeArgs := []string{}
	if paths.Scope != transcriptionservice.ScopeSystem {
		scopeArgs = append(scopeArgs, "--user")
	}
	switch action {
	case "start":
		if _, err := runServiceCommand(ctx, "systemctl", append(scopeArgs, "daemon-reload")...); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "systemctl", append(scopeArgs, "enable", "--now", unit)...)
	case "restart":
		if _, err := runServiceCommand(ctx, "systemctl", append(scopeArgs, "daemon-reload")...); err != nil {
			return "", err
		}
		if _, err := runServiceCommand(ctx, "systemctl", append(scopeArgs, "enable", unit)...); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "systemctl", append(scopeArgs, "restart", unit)...)
	case "stop":
		_, err := runServiceCommand(ctx, "systemctl", append(scopeArgs, "disable", "--now", unit)...)
		if err != nil && !strings.Contains(strings.ToLower(err.Error()), "not loaded") && !strings.Contains(strings.ToLower(err.Error()), "not found") {
			return "", err
		}
		return "stopped", nil
	default:
		return "", fmt.Errorf("unsupported systemctl action %q", action)
	}
}

func transcriptionServiceRunning(ctx context.Context, platform transcriptionservice.Platform, paths transcriptionservice.Paths) (bool, string) {
	switch platform {
	case transcriptionservice.PlatformMacOS:
		domain := fmt.Sprintf("gui/%d", os.Getuid())
		target := domain + "/" + transcriptionservice.LaunchAgentLabel
		if _, err := runServiceCommand(ctx, "launchctl", "print", target); err != nil {
			return false, "inactive"
		}
		return true, "active"
	case transcriptionservice.PlatformLinux:
		args := []string{"is-active", transcriptionservice.SystemdUnitName}
		if paths.Scope != transcriptionservice.ScopeSystem {
			args = append([]string{"--user"}, args...)
		}
		output, err := runServiceCommand(ctx, "systemctl", args...)
		if err != nil {
			return false, strings.TrimSpace(output)
		}
		return strings.TrimSpace(output) == "active", strings.TrimSpace(output)
	default:
		return false, "unsupported"
	}
}

func runServiceCommand(ctx context.Context, name string, args ...string) (string, error) {
	result, err := runBoundedExternalCommand(ctx, name, args...)
	if err != nil {
		var pathErr *exec.Error
		if errors.As(err, &pathErr) {
			return "", fmt.Errorf("%s is required for transcription service management: %w", name, err)
		}
		message := boundedExternalCommandDiagnostic(result, err)
		if errors.Is(err, errExternalProcessOutputTooLarge) {
			return "", fmt.Errorf("%s %s: %s: %w", name, strings.Join(args, " "), message, err)
		}
		return message, fmt.Errorf("%s %s: %s", name, strings.Join(args, " "), message)
	}
	return result.combinedOutput(), nil
}
