package cli

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/pankaj28843/cdp-cli/internal/transcriptionapi"
	"github.com/pankaj28843/cdp-cli/internal/transcriptionservice"
	"github.com/spf13/cobra"
)

func (a *app) newTranscriptionServiceCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "service",
		Short: "Install and control the user-level transcription API service",
		Long: "Manage cdp transcription serve as a per-user native service. macOS uses a LaunchAgent; " +
			"Linux uses systemd --user. The service reads its configuration from environment values " +
			"generated by install and restarts after transient process failures.",
		Example: "  cdp transcription service install --address 0.0.0.0:28765\n" +
			"  cdp transcription service status\n" +
			"  cdp transcription service uninstall",
	}
	cmd.AddCommand(a.newTranscriptionServiceInstallCommand())
	cmd.AddCommand(a.newTranscriptionServiceStartCommand("start", "Start and enable the user-level transcription API service"))
	cmd.AddCommand(a.newTranscriptionServiceStartCommand("restart", "Restart the user-level transcription API service"))
	cmd.AddCommand(a.newTranscriptionServiceStopCommand())
	cmd.AddCommand(a.newTranscriptionServiceStatusCommand())
	cmd.AddCommand(a.newTranscriptionServiceUninstallCommand())
	return cmd
}

func (a *app) newTranscriptionServiceInstallCommand() *cobra.Command {
	var address string
	var httpAddress string
	var token string
	var provider string
	var allowedProviders []string
	var localBaseURL string
	var localRealtimeBaseURL string
	var localAPIKey string
	var maxAudioBytes int64
	var authRefreshInterval time.Duration
	var persistAudio bool
	var tlsCertFile string
	var tlsKeyFile string
	var tlsSelfSigned bool
	var tlsHosts []string
	var tlsRegenerate bool
	var binaryPath string
	var start bool
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Write the native user service and start it",
		Long: "Write a LaunchAgent plist on macOS or a systemd --user unit plus owner-only " +
			"environment file on Linux. Installation is idempotent and starts the service by default. " +
			"Leave --token empty for a private no-auth demo, or set it before exposing the listener.",
		Example: "  cdp transcription service install --address 0.0.0.0:28765 --start\n" +
			"  cdp transcription service install --address 0.0.0.0:28765 --token lan-test\n" +
			"  cdp transcription service install --address 0.0.0.0:28765 --tls-self-signed --tls-host 192.168.5.249",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			platform, paths, config, err := a.transcriptionServiceConfig(binaryPath, address, httpAddress, token, provider, allowedProviders, localBaseURL, localRealtimeBaseURL, localAPIKey, maxAudioBytes, authRefreshInterval, persistAudio, tlsCertFile, tlsKeyFile)
			if err != nil {
				return err
			}
			if err := os.MkdirAll(config.StateDir, 0o700); err != nil {
				return fmt.Errorf("create transcription service state directory: %w", err)
			}
			tlsFiles, err := configureTranscriptionTLS(config.StateDir, config.TLSCertFile, config.TLSKeyFile, tlsSelfSigned, tlsHosts, tlsRegenerate)
			if err != nil {
				return err
			}
			config.TLSCertFile = tlsFiles.CertFile
			config.TLSKeyFile = tlsFiles.KeyFile
			artifacts, err := transcriptionservice.Render(platform, config, paths)
			if err != nil {
				return err
			}
			if err := writeTranscriptionServiceArtifacts(artifacts, paths.LogDirectory); err != nil {
				return err
			}
			if start {
				if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "restart", paths); err != nil {
					return err
				}
			}
			return a.render(cmd.Context(), "transcription service installed", map[string]any{
				"platform":         platform,
				"service":          serviceName(platform),
				"started":          start,
				"address":          config.Address,
				"http_address":     config.HTTPAddress,
				"provider":         config.Provider,
				"token_configured": strings.TrimSpace(config.Token) != "",
				"audio_persisted":  config.PersistAudio,
				"tls_enabled":      strings.TrimSpace(config.TLSCertFile) != "",
				"tls_cert_file":    tlsFiles.CertFile,
				"tls_hosts":        tlsFiles.Hosts,
				"tls_reused":       tlsFiles.Reused,
				"demo_url":         preferredDemoURL(config.Address, strings.TrimSpace(config.TLSCertFile) != "", tlsFiles.Hosts),
				"demo_urls":        demoURLs(config.Address, strings.TrimSpace(config.TLSCertFile) != "", tlsFiles.Hosts),
				"artifacts":        artifactPaths(artifacts),
			})
		},
	}
	cmd.Flags().StringVar(&address, "address", envDefault("CDP_TRANSCRIPTION_ADDRESS", transcriptionapi.DefaultListenAddress), "listen address; use 0.0.0.0:28765 for LAN dogfooding")
	cmd.Flags().StringVar(&httpAddress, "http-address", os.Getenv("CDP_TRANSCRIPTION_HTTP_ADDRESS"), "optional plain-HTTP listener; use a distinct port for explicit private-LAN/Tailscale access")
	cmd.Flags().StringVar(&token, "token", os.Getenv("CDP_TRANSCRIPTION_API_TOKEN"), "optional bearer token; leave blank for a private no-auth demo")
	cmd.Flags().StringVar(&provider, "default-provider", envDefault("CDP_TRANSCRIPTION_PROVIDER", string(transcriptionapi.ProviderLocal)), "default provider: local, chatgpt-web, or microsoft-365-web")
	cmd.Flags().StringSliceVar(&allowedProviders, "providers", envStringSlice("CDP_TRANSCRIPTION_PROVIDERS"), "provider allowlist persisted into the user service; repeat or comma-separate")
	cmd.Flags().StringVar(&localBaseURL, "local-base-url", os.Getenv("CDP_TRANSCRIPTION_LOCAL_BASE_URL"), "local OpenAI-compatible provider base URL, usually ending in /v1")
	cmd.Flags().StringVar(&localRealtimeBaseURL, "local-realtime-base-url", os.Getenv("CDP_TRANSCRIPTION_LOCAL_REALTIME_BASE_URL"), "optional local realtime provider base URL, usually ending in /v1")
	cmd.Flags().StringVar(&localAPIKey, "local-api-key", os.Getenv("CDP_TRANSCRIPTION_LOCAL_API_KEY"), "API key for the configured local provider")
	cmd.Flags().Int64Var(&maxAudioBytes, "max-audio-bytes", envInt64("CDP_TRANSCRIPTION_MAX_AUDIO_BYTES", transcriptionapi.DefaultMaxAudioBytes), "maximum retained audio-cache bytes")
	cmd.Flags().DurationVar(&authRefreshInterval, "auth-refresh-interval", envDuration("CDP_TRANSCRIPTION_AUTH_REFRESH_INTERVAL", transcriptionapi.DefaultAuthRefreshInterval), "shared recurring freshness check for online providers")
	cmd.Flags().BoolVar(&persistAudio, "persist-audio", envBool("CDP_TRANSCRIPTION_PERSIST_AUDIO"), "retain uploaded audio under the state directory; default is ephemeral transaction media")
	cmd.Flags().StringVar(&tlsCertFile, "tls-cert", os.Getenv("CDP_TRANSCRIPTION_TLS_CERT"), "TLS certificate file; provide with --tls-key for HTTPS microphone access over LAN")
	cmd.Flags().StringVar(&tlsKeyFile, "tls-key", os.Getenv("CDP_TRANSCRIPTION_TLS_KEY"), "TLS private key file; provide with --tls-cert")
	cmd.Flags().BoolVar(&tlsSelfSigned, "tls-self-signed", false, "generate or reuse a private-LAN self-signed certificate under the cdp state directory")
	cmd.Flags().StringSliceVar(&tlsHosts, "tls-host", nil, "DNS name or IP to include in a self-signed certificate; repeat for multiple names")
	cmd.Flags().BoolVar(&tlsRegenerate, "tls-regenerate", false, "replace the generated self-signed certificate and key")
	cmd.Flags().StringVar(&binaryPath, "binary", "", "absolute cdp binary path; defaults to the running executable")
	cmd.Flags().BoolVar(&start, "start", true, "start and enable the service after installing its files")
	return cmd
}

func (a *app) newTranscriptionServiceStartCommand(name, short string) *cobra.Command {
	return &cobra.Command{
		Use:   name,
		Short: short,
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			platform, paths, err := a.transcriptionServicePaths()
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, name, paths); err != nil {
				return err
			}
			return a.render(cmd.Context(), "transcription service "+name+" complete", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) newTranscriptionServiceStopCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "stop",
		Short: "Stop the user-level transcription API service",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			platform, paths, err := a.transcriptionServicePaths()
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "stop", paths); err != nil {
				return err
			}
			return a.render(cmd.Context(), "transcription service stopped", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) newTranscriptionServiceStatusCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show user-level transcription API service status",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			platform, paths, err := a.transcriptionServicePaths()
			if err != nil {
				return err
			}
			installed := serviceInstalled(platform, paths)
			running, detail := transcriptionServiceRunning(cmd.Context(), platform, paths)
			tlsEnabled := transcriptionServiceTLSConfigured(platform, paths)
			return a.render(cmd.Context(), "transcription service status", map[string]any{
				"platform":    platform,
				"service":     serviceName(platform),
				"installed":   installed,
				"running":     running,
				"detail":      detail,
				"tls_enabled": tlsEnabled,
				"demo_url":    demoURL(transcriptionapi.DefaultListenAddress, tlsEnabled),
				"artifacts":   map[string]string{"launch_agent": paths.LaunchAgent, "systemd_unit": paths.SystemdUnit, "environment": paths.Environment},
			})
		},
	}
}

func (a *app) newTranscriptionServiceUninstallCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "uninstall",
		Short: "Stop and remove the user-level transcription API service",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			platform, paths, err := a.transcriptionServicePaths()
			if err != nil {
				return err
			}
			if _, err := runTranscriptionServiceAction(cmd.Context(), platform, "stop", paths); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			for _, path := range serviceArtifactPaths(platform, paths) {
				if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
					return fmt.Errorf("remove transcription service artifact %s: %w", path, err)
				}
			}
			return a.render(cmd.Context(), "transcription service uninstalled", map[string]any{
				"platform": platform,
				"service":  serviceName(platform),
			})
		},
	}
}

func (a *app) transcriptionServicePaths() (transcriptionservice.Platform, transcriptionservice.Paths, error) {
	platform, err := transcriptionservice.CurrentPlatform()
	if err != nil {
		return "", transcriptionservice.Paths{}, err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", transcriptionservice.Paths{}, fmt.Errorf("resolve home directory: %w", err)
	}
	paths, err := transcriptionservice.PathsForHome(home)
	if err != nil {
		return "", transcriptionservice.Paths{}, err
	}
	return platform, paths, nil
}

func (a *app) transcriptionServiceConfig(binaryPath, address, httpAddress, token, provider string, allowedProviders []string, localBaseURL, localRealtimeBaseURL, localAPIKey string, maxAudioBytes int64, authRefreshInterval time.Duration, persistAudio bool, tlsCertFile, tlsKeyFile string) (transcriptionservice.Platform, transcriptionservice.Paths, transcriptionservice.Config, error) {
	platform, paths, err := a.transcriptionServicePaths()
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, err
	}
	stateStore, err := a.stateStore()
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, err
	}
	if strings.TrimSpace(binaryPath) == "" {
		binaryPath, err = os.Executable()
		if err != nil {
			return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("resolve running cdp executable: %w", err)
		}
	}
	binaryPath, err = filepath.Abs(binaryPath)
	if err != nil {
		return "", transcriptionservice.Paths{}, transcriptionservice.Config{}, fmt.Errorf("resolve cdp executable path: %w", err)
	}
	config := transcriptionservice.Config{
		BinaryPath:           binaryPath,
		StateDir:             stateStore.Dir,
		Address:              strings.TrimSpace(address),
		HTTPAddress:          strings.TrimSpace(httpAddress),
		Provider:             strings.TrimSpace(provider),
		AllowedProviders:     append([]string(nil), allowedProviders...),
		BrowserMode:          a.browserModeName(),
		Display:              strings.TrimSpace(os.Getenv("DISPLAY")),
		XAuthority:           strings.TrimSpace(os.Getenv("XAUTHORITY")),
		AllowOverBudget:      a.opts.allowOverBudget,
		LocalBaseURL:         strings.TrimSpace(localBaseURL),
		LocalRealtimeBaseURL: strings.TrimSpace(localRealtimeBaseURL),
		LocalAPIKey:          strings.TrimSpace(localAPIKey),
		MaxAudioBytes:        maxAudioBytes,
		AuthRefreshInterval:  authRefreshInterval,
		PersistAudio:         persistAudio,
		TLSCertFile:          strings.TrimSpace(tlsCertFile),
		TLSKeyFile:           strings.TrimSpace(tlsKeyFile),
		Path:                 os.Getenv("PATH"),
	}
	config.Token = strings.TrimSpace(token)
	return platform, paths, config, nil
}

func writeTranscriptionServiceArtifacts(artifacts []transcriptionservice.Artifact, logDirectory string) error {
	if err := os.MkdirAll(logDirectory, 0o700); err != nil {
		return fmt.Errorf("create transcription service log directory: %w", err)
	}
	for _, artifact := range artifacts {
		if err := os.MkdirAll(filepath.Dir(artifact.Path), 0o700); err != nil {
			return fmt.Errorf("create transcription service directory for %s: %w", artifact.Path, err)
		}
		if err := os.WriteFile(artifact.Path, artifact.Data, artifact.Mode); err != nil {
			return fmt.Errorf("write transcription service artifact %s: %w", artifact.Path, err)
		}
		if err := os.Chmod(artifact.Path, artifact.Mode); err != nil {
			return fmt.Errorf("set transcription service artifact mode %s: %w", artifact.Path, err)
		}
	}
	return nil
}

func artifactPaths(artifacts []transcriptionservice.Artifact) []string {
	paths := make([]string, 0, len(artifacts))
	for _, artifact := range artifacts {
		paths = append(paths, artifact.Path)
	}
	return paths
}

func serviceArtifactPaths(platform transcriptionservice.Platform, paths transcriptionservice.Paths) []string {
	if platform == transcriptionservice.PlatformMacOS {
		return []string{paths.LaunchAgent}
	}
	return []string{paths.SystemdUnit, paths.Environment}
}

func serviceInstalled(platform transcriptionservice.Platform, paths transcriptionservice.Paths) bool {
	for _, path := range serviceArtifactPaths(platform, paths) {
		if _, err := os.Stat(path); err != nil {
			return false
		}
	}
	return true
}

func serviceName(platform transcriptionservice.Platform) string {
	if platform == transcriptionservice.PlatformMacOS {
		return transcriptionservice.LaunchAgentLabel
	}
	return transcriptionservice.SystemdUnitName
}

func runTranscriptionServiceAction(ctx context.Context, platform transcriptionservice.Platform, action string, paths transcriptionservice.Paths) (string, error) {
	switch platform {
	case transcriptionservice.PlatformMacOS:
		return runLaunchctlAction(ctx, action, paths)
	case transcriptionservice.PlatformLinux:
		return runSystemctlAction(ctx, action, paths)
	default:
		return "", fmt.Errorf("unsupported transcription service platform %q", platform)
	}
}

func runLaunchctlAction(ctx context.Context, action string, paths transcriptionservice.Paths) (string, error) {
	domain := fmt.Sprintf("gui/%d", os.Getuid())
	target := domain + "/" + transcriptionservice.LaunchAgentLabel
	switch action {
	case "start":
		if _, err := runServiceCommand(ctx, "launchctl", "print", target); err != nil {
			if err := bootstrapLaunchAgent(ctx, domain, paths.LaunchAgent); err != nil {
				return "", err
			}
		}
		return runServiceCommand(ctx, "launchctl", "kickstart", "-k", target)
	case "restart":
		_, _ = runServiceCommand(ctx, "launchctl", "bootout", target)
		if err := bootstrapLaunchAgent(ctx, domain, paths.LaunchAgent); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "launchctl", "kickstart", "-k", target)
	case "stop":
		_, err := runServiceCommand(ctx, "launchctl", "bootout", target)
		if err != nil && !strings.Contains(strings.ToLower(err.Error()), "could not find service") {
			return "", err
		}
		return "stopped", nil
	default:
		return "", fmt.Errorf("unsupported launchctl action %q", action)
	}
}

// bootstrapLaunchAgent prefers the modern bootstrap API but keeps a legacy
// load fallback for macOS versions/configurations that return an opaque I/O
// error when bootstrapping a per-user LaunchAgent. Both paths still register
// the same plist; the fallback is only for launchctl compatibility.
func bootstrapLaunchAgent(ctx context.Context, domain, plistPath string) error {
	if _, err := runServiceCommand(ctx, "launchctl", "bootstrap", domain, plistPath); err == nil {
		return nil
	} else {
		if _, loadErr := runServiceCommand(ctx, "launchctl", "load", plistPath); loadErr == nil {
			return nil
		} else {
			return fmt.Errorf("launchctl bootstrap failed: %w; legacy load fallback failed: %v", err, loadErr)
		}
	}
}

func runSystemctlAction(ctx context.Context, action string, paths transcriptionservice.Paths) (string, error) {
	unit := transcriptionservice.SystemdUnitName
	switch action {
	case "start":
		if _, err := runServiceCommand(ctx, "systemctl", "--user", "daemon-reload"); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "systemctl", "--user", "enable", "--now", unit)
	case "restart":
		if _, err := runServiceCommand(ctx, "systemctl", "--user", "daemon-reload"); err != nil {
			return "", err
		}
		if _, err := runServiceCommand(ctx, "systemctl", "--user", "enable", unit); err != nil {
			return "", err
		}
		return runServiceCommand(ctx, "systemctl", "--user", "restart", unit)
	case "stop":
		_, err := runServiceCommand(ctx, "systemctl", "--user", "disable", "--now", unit)
		if err != nil && !strings.Contains(strings.ToLower(err.Error()), "not loaded") && !strings.Contains(strings.ToLower(err.Error()), "not found") {
			return "", err
		}
		return "stopped", nil
	default:
		return "", fmt.Errorf("unsupported systemctl action %q", action)
	}
}

func transcriptionServiceRunning(ctx context.Context, platform transcriptionservice.Platform, paths transcriptionservice.Paths) (bool, string) {
	switch platform {
	case transcriptionservice.PlatformMacOS:
		domain := fmt.Sprintf("gui/%d", os.Getuid())
		target := domain + "/" + transcriptionservice.LaunchAgentLabel
		if _, err := runServiceCommand(ctx, "launchctl", "print", target); err != nil {
			return false, "inactive"
		}
		return true, "active"
	case transcriptionservice.PlatformLinux:
		output, err := runServiceCommand(ctx, "systemctl", "--user", "is-active", transcriptionservice.SystemdUnitName)
		if err != nil {
			return false, strings.TrimSpace(output)
		}
		return strings.TrimSpace(output) == "active", strings.TrimSpace(output)
	default:
		return false, "unsupported"
	}
}

func runServiceCommand(ctx context.Context, name string, args ...string) (string, error) {
	if _, err := exec.LookPath(name); err != nil {
		return "", fmt.Errorf("%s is required for transcription service management: %w", name, err)
	}
	command := exec.CommandContext(ctx, name, args...)
	output, err := command.CombinedOutput()
	if err != nil {
		message := strings.TrimSpace(string(output))
		if message == "" {
			message = err.Error()
		}
		return message, fmt.Errorf("%s %s: %s", name, strings.Join(args, " "), message)
	}
	return string(output), nil
}
